apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    olm.skipRange: '>=1.1.0 <1.4.4'
    alm-examples: |-
      [
        {
          "apiVersion": "operator.ibm.com/v1alpha1",
          "kind": "NginxIngress",
          "metadata": {
            "name": "default"
          },
          "spec": {
            "defaultBackend": {
              "imageRegistry": "quay.io/opencloudio",
              "image": {
                "pullPolicy": "IfNotPresent",
                "repository": "default-http-backend@sha256",
                "tag": "df00d527d36c67d8746f35d346edd600d2fb65db70ced420abc3de255eb51afd"
              },
              "name": "default-http-backend",
              "nodeSelector": {},
              "replicaCount": 1,
              "replicas": 1,
              "resources": {
                "requests": {
                  "cpu": "20m",
                  "memory": "64Mi"
                },
                "limits": {
                  "cpu": "50m",
                  "memory": "128Mi"
                }
              },
              "tolerations": []
            },
            "fips_enabled": false,
            "ingress": {
              "annotations": {},
              "config": {
                "disable-access-log": "true",
                "keep-alive-requests": "10000",
                "server-tokens": "false",
                "upstream-keepalive-connections": "64"
              },
              "extraArgs": {},
              "hostNetwork": false,
              "hostPort": false,
              "httpPort": 7080,
              "httpsPort": 7443,
              "imageRegistry": "quay.io/opencloudio",
              "image": {
                "pullPolicy": "IfNotPresent",
                "repository": "nginx-ingress-controller@sha256",
                "tag": "b1aa46ae49591025efea19dc894460433241943031b7c5221a549c0a5c163363"
              },
              "name": "nginx-ingress-controller",
              "nodeSelector": {},
              "replicaCount": 1,
              "replicas": 1,
              "resources": {
                "requests": {
                  "cpu": "50m",
                  "memory": "150Mi"
                },
                "limits": {
                  "cpu": "200m",
                  "memory": "512Mi"
                }
              },
              "routeHost": "",
              "tolerations": []
            },
            "init": {
              "imageRegistry": "quay.io/opencloudio",
              "image": {
                "pullPolicy": "IfNotPresent",
                "repository": "icp-initcontainer@sha256",
                "tag": "60699eab29e17db05963ed19f8bbd0c6124b2b6d19c2d2563698660f9f46997e"
              }
            },
            "kubectl": {
              "resources": {
                "requests": {
                  "cpu": "50m",
                  "memory": "64Mi"
                },
                "limits": {
                  "cpu": "200m",
                  "memory": "512Mi"
                }
              },
              "imageRegistry": "quay.io/opencloudio",
              "image": {
                "repository": "kubectl@sha256",
                "tag": "3aebec68f70b466d3e18a1bad8dd54c9220887a5fe1d779fb8a10aca4cbe3347"
              }
            }
          }
        }
      ]
    capabilities: Basic Install
    categories: Developer Tools
    certified: "false"
    containerImage: quay.io/opencloudio/ibm-ingress-nginx-operator:1.4.4
    createdAt: "2021-11-01T09:59:00Z"
    description: Operator for managing deployment of ingress nginx service.
    repository: https://github.com/IBM/ibm-ingress-nginx-operator.git
    support: IBM
  labels:
    operatorframework.io/arch.amd64: supported
    operatorframework.io/arch.ppc64le: supported
    operatorframework.io/arch.s390x: supported
    operatorframework.io/os.linux: supported
  name: ibm-ingress-nginx-operator.v1.4.4
  namespace: placeholder
spec:
  relatedImages:
    - name: NGINX_INGRESS_CONTROLLER_IMAGE
      image: quay.io/opencloudio/nginx-ingress-controller:0.23.15
    - name: DEFAULT_HTTP_BACKEND_IMAGE
      image: quay.io/opencloudio/default-http-backend:1.5.9
    - name: KUBECTL_IMAGE
      image: quay.io/opencloudio/kubectl:v1.15.9.6
    - name: IBM_INGRESS_NGINX_OPERATOR_IMAGE
      image: quay.io/opencloudio/ibm-ingress-nginx-operator:1.4.4
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: NginxIngress is the Schema for the nginxingress API
      group: operator.ibm.com
      kind: NginxIngress
      name: nginxingresses.operator.ibm.com
      version: v1alpha1
      displayName: IBM Ingress nginx Operator
      resources:
      - kind: Deployment
        name: ibm-ingress-nginx-operator
        version: v1
      - kind: Service
        name: ibm-ingress-nginx-operator
        version: v1
      - kind: Configmap
        name: ibm-ingress-nginx-operator
        version: v1
      specDescriptors:
      - description: Image of Ingress nginx controller
        displayName: Image of Ingress nginx controller
        path: spec.ingress.image
      - description: Image of Default http backend
        displayName: Image of Default http backend
        path: spec.defaultBackend.image
      - description: Number of instance for Ingress nginx controller
        displayName: Replica of Ingress nginx controller
        path: spec.ingress.replicaCount
      - description: Number of instance for Ingress nginx controller
        displayName: Replicas of Ingress nginx controller
        path: spec.ingress.replicas
      - description: Whether to enable FIPS encryption
        displayName: Enable FIPS encryption
        path: spec.fips_enabled
  description: "**Important:** Do not install this operator directly. Only install this operator using the IBM Common Services Operator. For more information about installing this operator and other Common Services operators, see [Installer documentation](http://ibm.biz/cpcs_opinstall).\n\n If you are using this operator as part of an IBM Cloud Pak, see the documentation for that IBM Cloud Pak to learn more about how to install and use the operator service. For more information about IBM Cloud Paks, see [IBM Cloud Paks that use Common Services](http://ibm.biz/cpcs_cloudpaks).\n\n You can use the IBM Ingress Nginx Operator to install the IBM  Ingress Nginx service (controller), which provides a Helm chart repository for storing and supplying IBM and local charts. \n\n The Ingress Nginx Operator installs the following components: \n- The Ingress Nginx service (controller). \n- A deployment to running Ingress Ngnix Controller pod. \n- A service default-http-backend. \n- A configmap nginx-ingress-controller. \n- A route cp-proxy.  \n\nFor more information about the available IBM Cloud Platform Common Services, see the [IBM Knowledge Center](http://ibm.biz/cpcsdocs). \n## Supported platforms \n\n Red Hat OpenShift Container Platform 4.3 or newer installed on one of the following platforms: \n\n- Linux x86_64 \n- Linux on Power (ppc64le) \n- Linux on IBM Z and LinuxONE \n##  Prerequisites\n\n The Ingress Nginx service has dependencies on other IBM Cloud Platform Common Services. Before you install this operator, you need to first install the operator dependencies and prerequisites: \n\n- For the list of operator dependencies, see the IBM Knowledge Center Common Services dependencies documentation. \n- For the list of prerequisites for installing the operator, see the IBM Knowledge Center Preparing to install services documentation. \n## Documentation \n\n To install the operator with the IBM Common Services Operator follow the the installation and configuration instructions within the IBM Knowledge Center. \n- If you are using the operator as part of an IBM Cloud Pak, see the documentation for that IBM Cloud Pak, for a list of IBM Cloud Paks, see [IBM Cloud Paks that use Common Services](http://ibm.biz/cpcs_cloudpaks). \n- If you are using the operator with an IBM Containerized Software, see the IBM Cloud Platform Common Services Knowledge Center [Installer documentation](http://ibm.biz/cpcs_opinstall)."
  displayName: IBM Ingress Nginx Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        # ngin-ingress controller needs to get namespace for the current watched namespace
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        # ngin-ingress controller needs to read node info to update ingress status
        - apiGroups:
          - ""
          resources:
          - nodes
          verbs:
          - get
          - list
          - watch
        serviceAccountName: nginx-ingress
      permissions:
      - rules:
        - apiGroups:
          - operator.ibm.com
          resources:
          - nginxingresses
          - nginxingresses/finalizers
          - nginxingresses/status
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - create
          - delete
          - get
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resourceNames:
          - ibm-ingress-nginx-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - serviceaccounts
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: ibm-ingress-nginx-operator
      - rules:
        - apiGroups:
          - ""
          resources:
          - endpoints
          - pods
          - secrets
          - services
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - create
          - get
          - list
          - watch
          - patch
          - update
        - apiGroups:
          - ""
          resources:
          - configmaps
          resourceNames:
          # Defaults to "<election-id>-<ingress-class>"
          # Here: "<ingress-controller-leader>-<nginx>"
          # This has to be adapted if you change either parameter
          # when launching the nginx-ingress-controller.
          - "ingress-controller-leader-nginx"
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        - apiGroups:
          - "extensions"
          - "networking.k8s.io"
          resources:
          - ingresses
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - "extensions"
          - "networking.k8s.io"
          resources:
          - ingresses/status
          verbs:
          - update
        serviceAccountName: nginx-ingress
      deployments:
      - name: ibm-ingress-nginx-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: ibm-ingress-nginx-operator
          strategy: {}
          template:
            metadata:
              labels:
                intent: projected
                name: ibm-ingress-nginx-operator
                app.kubernetes.io/managed-by: ""
                app.kubernetes.io/name: "ibm-ingress-nginx-operator"
              annotations:
                productName: "IBM Cloud Platform Common Services"
                productID: "068a62892a1e4db39641342e592daa25"
                productMetric: "FREE"                
            spec:
              containers:
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    configMapKeyRef:
                      name: namespace-scope
                      key: namespaces
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: ibm-ingress-nginx-operator
                - name: INGRESS_IMAGE_DIGEST
                  value: quay.io/opencloudio/nginx-ingress-controller@sha256:b1aa46ae49591025efea19dc894460433241943031b7c5221a549c0a5c163363
                - name: DEFAULT_BACKEND_IMAGE_DIGEST
                  value: quay.io/opencloudio/default-http-backend@sha256:df00d527d36c67d8746f35d346edd600d2fb65db70ced420abc3de255eb51afd
                - name: KUBECTL_IMAGE_DIGEST
                  value: quay.io/opencloudio/kubectl@sha256:3aebec68f70b466d3e18a1bad8dd54c9220887a5fe1d779fb8a10aca4cbe3347
                image: quay.io/opencloudio/ibm-ingress-nginx-operator:latest
                imagePullPolicy: Always
                name: ibm-ingress-nginx-operator
                resources: {}
              serviceAccountName: ibm-ingress-nginx-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: stable
  provider:
    name: IBM
  replaces: ibm-ingress-nginx-operator.v1.4.3
  version: 1.4.4
