apiVersion: operator.ibm.com/v1alpha1
kind: NginxIngress
metadata:
  name: default
spec:
  ingress:
    name: nginx-ingress-controller
    replicaCount: 1
    hostNetwork: false
    hostPort: false
    httpPort: 80
    httpsPort: 443
    routeHost: cp-proxy.apps.ibm.com
    imageRegistry: quay.io/opencloudio
    image:
      repository: nginx-ingress-controller
      tag: 0.23.4
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 50m
        memory: 150Mi
      limits:
        cpu: 200m
        memory: 256Mi
    config:
      disable-access-log: 'true'
      keep-alive-requests: '10000'
      upstream-keepalive-connections: '64'
      server-tokens: 'false'
    extraArgs: {}
    annotations: {}
    nodeSelector: {}
    tolerations: []
  defaultBackend:
    name: default-http-backend
    replicaCount: 1
    image:
      imageRegistry: quay.io/opencloudio
      repository: default-http-backend
      tag: 1.5.3
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 20m
        memory: 64Mi
      limits:
        cpu: 50m
        memory: 128Mi
    nodeSelector: {}
    tolerations: []
  init:
    imageRegistry: quay.io/opencloudio
    image:
      repository: icp-initcontainer
      tag: 1.0.0-build.2
      pullPolicy: IfNotPresent
  kubectl:
    imageRegistry: quay.io/opencloudio
    image:
      repository: kubectl
      tag: v1.15.9
  fips_enabled: false
