apiVersion: operator.ibm.com/v1alpha1
kind: NginxIngress
metadata:
  name: default
spec:
  ingress:
    name: nginx-ingress-controller
    replicaCount: 1
    replicas: 1
    hostNetwork: false
    hostPort: false
    httpPort: 7080
    httpsPort: 7443
    routeHost: ""
    imageRegistry: quay.io/opencloudio
    image:
      repository: nginx-ingress-controller
      tag: 0.23.5
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 50m
        memory: 150Mi
      limits:
        cpu: 200m
        memory: 512Mi
    config:
      disable-access-log: 'true'
      keep-alive-requests: '10000'
      upstream-keepalive-connections: '64'
      server-tokens: 'false'
    extraArgs: {}
    annotations: {}
    nodeSelector: {}
    tolerations: []
  defaultBackend:
    name: default-http-backend
    replicaCount: 1
    replicas: 1
    image:
      imageRegistry: quay.io/opencloudio
      repository: default-http-backend
      tag: 1.5.4
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 20m
        memory: 64Mi
      limits:
        cpu: 50m
        memory: 128Mi
    nodeSelector: {}
    tolerations: []
  fips_enabled: false
